# -*- coding: utf-8 -*-
"""Conchita_EDEM_LangChain_Tools_Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IkhMhXBBys6AyQ0Lu3GsTvW60gabBBOh
"""

pip install -q langchain_google_genai

pip install -U langchain-community

import getpass
import os
if 'GOOGLE_API_KEY' not in os.environ:
    os.environ['GOOGLE_API_KEY'] = getpass.getpass('Provide your Google API Key: ')

from langchain_google_genai import ChatGoogleGenerativeAI

chat = ChatGoogleGenerativeAI(model='gemini-2.5-flash')

"""### Tools

#### Creating own custom tool
"""

from langchain.tools import BaseTool, tool
from langchain_core.tools import StructuredTool

@tool
def name_of_tool(input: str) -> str:
    """Tool_Description"""
    return "Result"

print(name_of_tool.name)
print(name_of_tool.description)
print(name_of_tool.args)

"""#### Defining, Binding and Calling the tool"""

@tool
def conchita_coins(input: float) -> float:
    """Use this tool to convert USD to Conchita Academy coins"""
    return 1.3*(float(input))

chat_bind_tools = chat.bind_tools([conchita_coins])

result = chat_bind_tools.invoke("How many Conchita academy coins can I get for USD10")
result

result.tool_calls

tool_mapping = {
    'conchita_coins': conchita_coins
}
tool_mapping

tool = tool_mapping[result.tool_calls[0]["name"]]

tool_output = tool.invoke(result.tool_calls[0]["args"])

tool_output

"""### Using in-built tools

#### DuckDuckGo Search tool
"""

pip install -U ddgs

from langchain_community.tools import DuckDuckGoSearchRun
search = DuckDuckGoSearchRun()

search.name, search.description

search.run("What are tools in Langchain?")

from langchain_community.tools import DuckDuckGoSearchResults
search = DuckDuckGoSearchResults()
search.invoke("What are tools in Langchain?")

"""### Wikipedia"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install --upgrade --quiet  wikipedia

from langchain_community.tools.wikipedia.tool import WikipediaQueryRun
from langchain_community.utilities import WikipediaAPIWrapper

wikipedia = WikipediaQueryRun(api_wrapper=WikipediaAPIWrapper())

wikipedia.invoke("LangChain")

"""### Agents"""

from langchain_classic.agents import AgentExecutor, create_tool_calling_agent
from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_messages(

      [  (
            "system",
            "You are a helpful assistant. For answering the user query, look for information using DuckDuckGo Search and Wikipedia and then give the final answer",
        ),
        ("human", "{input}"),


           ("placeholder", "{agent_scratchpad}"),

      ]
)
tools = [search, wikipedia]

agent = create_tool_calling_agent(chat, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor.invoke({"input": "When was Nelson Mandela born and what are some of his famous quotes?"})

"""#### Agent with memory"""

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "You are a helpful assistant. Based on user query and the chat history, look for information using DuckDuckGo Search and Wikipedia and then give the final answer",
        ),
        ("placeholder", "{history}"),
        ("human", "{input}"),
        ("placeholder", "{agent_scratchpad}"),
    ]
)

agent = create_tool_calling_agent(chat, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.chat_history import BaseChatMessageHistory
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_core.runnables import RunnableLambda

store = {}


def get_session_history(session_id: str) -> BaseChatMessageHistory:
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]


def ensure_string_output(agent_result: dict) -> dict:
    output_value = agent_result.get('output')
    if isinstance(output_value, list):
        concatenated_text = ""
        for item in output_value:
            if isinstance(item, dict) and item.get('type') == 'text':
                concatenated_text += item.get('text', '')
            elif isinstance(item, str):
                concatenated_text += item
        agent_result['output'] = concatenated_text
    elif not isinstance(output_value, str):
        agent_result['output'] = str(output_value)
    return agent_result

agent_executor_with_formatted_output = agent_executor | RunnableLambda(ensure_string_output)

agent_with_history = RunnableWithMessageHistory(
    agent_executor_with_formatted_output,
    get_session_history,
    input_messages_key="input",
    history_messages_key="history",
)

agent_with_history.invoke(
    {"input": "When was Nelson Mandela born?"},
    config={"configurable": {"session_id": "sess1"}},
)

result = agent_with_history.invoke(
    {"input": "What are some of his famous quotes?"},
    config={"configurable": {"session_id": "sess1"}},
)

result['output']